#!/usr/bin/env python3

import sys

def factorize(num):
    factors = []
    div = 2
    while num > 1:
        while num % div == 0:
            factors.append(div)
            num //= div
        div +=1
    return factors
def factorize_file(file_path):
    with open(file_path, 'r') as file:
        for line in file:
            num = int(line.strip())
            factors = factorize(num)
            if len(factors) >= 2:
                p, q = factors[0], factors[1]
                print(f"{num}={p}*{q}")
if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    input_file = sys.argv[1]
    factorize_file(input_file)
