#!/usr/bin/env python3

import sys

def factorize(val):
    i =2
    if val < 2:
        return
    factors = []
    while val % i:
        i += 1
    factors.append(i)
    val //= i
    factors.append(val)
    return factors
def factorize_file(file_path):
    with open(file_path, 'r') as file:
        for line in file:
            num = int(line.strip())
            factors = factorize(num)
            if len(factors) >= 2:
                p, q = factors[0], factors[1]
                print(f"{num}={q}*{p}")
if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: ./factors <file>")
        sys.exit(1)
    input_file = sys.argv[1]
    factorize_file(input_file)
