#!/usr/bin/env bash

factorize_rsa()
{
	local n=$1
	local i=2

	while (( i*i <= n )); do
		if (( n % i == 0)); then
			echo "$n=$(($n / i))*$i"
			return
		else
			i=$((i + 1))
		fi
	done
	echo "Cannot factorize $n into two prime numbers."
}
if [ $# -ne 1 ]; then
	echo 'Usage: rsa <file>'
	exit 1
fi
input_number="$1"
while read -r line; do
	factorize_rsa "$line"
done < "$input_number"
