#!/usr/bin/env python3

import sys

def trial_division(n):
    factors = []
    i = 2
    while i*i <= n:
        if n % i:
            i += 1
        else:
            n //= i
            factors.append(i)
    if n > 1:
        factors.append(n)
    return factors

def factorize_rsa(n):
    factors = trial_division(n)
    if len(factors) == 2:
        p, q = factors
        print(f"{n}={q}*{p}")
    else:
        print(f"Cannot factorize {n} into two prime numbers.")
if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: rsa <number>")
        sys.exit(1)
    input_file = sys.argv[1]
    with open(input_file) as f:
        for line in f:
            input_number = int(line.strip())
            factorize_rsa(input_number)
